/*
 * This file is generated by jOOQ.
 */
package com.exigent.verifycore.db.jooq.tables.records;


import com.exigent.verifycore.db.jooq.tables.Persona;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PersonaRecord extends UpdatableRecordImpl<PersonaRecord> implements Record5<Integer, String, String, String, String> {

    private static final long serialVersionUID = -1204374507;

    /**
     * Setter for <code>persona.id</code>.
     */
    public PersonaRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>persona.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>persona.externalId</code>.
     */
    public PersonaRecord setExternalid(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>persona.externalId</code>.
     */
    public String getExternalid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>persona.firstName</code>.
     */
    public PersonaRecord setFirstname(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>persona.firstName</code>.
     */
    public String getFirstname() {
        return (String) get(2);
    }

    /**
     * Setter for <code>persona.lastName</code>.
     */
    public PersonaRecord setLastname(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>persona.lastName</code>.
     */
    public String getLastname() {
        return (String) get(3);
    }

    /**
     * Setter for <code>persona.otherName</code>.
     */
    public PersonaRecord setOthername(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>persona.otherName</code>.
     */
    public String getOthername() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, String, String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, String, String, String, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Persona.PERSONA.ID;
    }

    @Override
    public Field<String> field2() {
        return Persona.PERSONA.EXTERNALID;
    }

    @Override
    public Field<String> field3() {
        return Persona.PERSONA.FIRSTNAME;
    }

    @Override
    public Field<String> field4() {
        return Persona.PERSONA.LASTNAME;
    }

    @Override
    public Field<String> field5() {
        return Persona.PERSONA.OTHERNAME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getExternalid();
    }

    @Override
    public String component3() {
        return getFirstname();
    }

    @Override
    public String component4() {
        return getLastname();
    }

    @Override
    public String component5() {
        return getOthername();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getExternalid();
    }

    @Override
    public String value3() {
        return getFirstname();
    }

    @Override
    public String value4() {
        return getLastname();
    }

    @Override
    public String value5() {
        return getOthername();
    }

    @Override
    public PersonaRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public PersonaRecord value2(String value) {
        setExternalid(value);
        return this;
    }

    @Override
    public PersonaRecord value3(String value) {
        setFirstname(value);
        return this;
    }

    @Override
    public PersonaRecord value4(String value) {
        setLastname(value);
        return this;
    }

    @Override
    public PersonaRecord value5(String value) {
        setOthername(value);
        return this;
    }

    @Override
    public PersonaRecord values(Integer value1, String value2, String value3, String value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PersonaRecord
     */
    public PersonaRecord() {
        super(Persona.PERSONA);
    }

    /**
     * Create a detached, initialised PersonaRecord
     */
    public PersonaRecord(Integer id, String externalid, String firstname, String lastname, String othername) {
        super(Persona.PERSONA);

        set(0, id);
        set(1, externalid);
        set(2, firstname);
        set(3, lastname);
        set(4, othername);
    }
}
