/*
 * This file is generated by jOOQ.
 */
package com.exigent.verifycore.db.jooq;


import com.exigent.verifycore.db.jooq.tables.Persona;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code></code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index PERSONA_PRIMARY = Indexes0.PERSONA_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index PERSONA_PRIMARY = Internal.createIndex("PRIMARY", Persona.PERSONA, new OrderField[] { Persona.PERSONA.ID }, true);
    }
}
