/*
 * This file is generated by jOOQ.
 */
package com.exigent.verifycore.db.jooq;


import com.exigent.verifycore.db.jooq.tables.Persona;
import com.exigent.verifycore.db.jooq.tables.records.PersonaRecord;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code></code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<PersonaRecord, Integer> IDENTITY_PERSONA = Identities0.IDENTITY_PERSONA;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<PersonaRecord> KEY_PERSONA_PRIMARY = UniqueKeys0.KEY_PERSONA_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<PersonaRecord, Integer> IDENTITY_PERSONA = Internal.createIdentity(Persona.PERSONA, Persona.PERSONA.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<PersonaRecord> KEY_PERSONA_PRIMARY = Internal.createUniqueKey(Persona.PERSONA, "KEY_persona_PRIMARY", Persona.PERSONA.ID);
    }
}
