/*
 * This file is generated by jOOQ.
 */
package com.exigent.verifycore.db.jooq;


import com.exigent.verifycore.db.jooq.tables.Persona;


/**
 * Convenience access to all tables in 
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>persona</code>.
     */
    public static final Persona PERSONA = Persona.PERSONA;
}
